#!/bin/bash

cd `dirname $0`
BASE=`pwd`
cd - >> /dev/null

source ${BASE}/../config.sh

oc delete all -n $HR_PROJECT -l app=hosted-workshop 2>/dev/null
oc delete oauthclient/hosted-workshop-console

echo -n "waiting for gitea pod to terminate..."
while [ $(oc get -n $HR_PROJECT po -l app=hosted-workshop -o name 2>/dev/null | wc -l) -gt 0 ]; do
  echo -n "."
  sleep 5
done
echo "done"

oc delete -n $HR_PROJECT bc/homeroom 2>/dev/null
oc delete -n $HR_PROJECT is/homeroom 2>/dev/null
oc delete -n $HR_PROJECT is/workshop-dashboard 2>/dev/null
oc delete -n $HR_PROJECT pvc/hosted-workshop-spawner-data 2>/dev/null
for sa in $(oc get -n $HR_PROJECT sa -o name 2>/dev/null | grep hosted-workshop-); do
  oc delete -n $HR_PROJECT $sa
done
for cm in $(oc get -n $HR_PROJECT cm -o name 2>/dev/null | grep hosted-workshop-); do
  oc delete -n $HR_PROJECT $cm
done

if [ $(oc get all -n $HR_PROJECT --no-headers 2>/dev/null | wc -l) -eq 0 ]; then
  oc delete project $HR_PROJECT
  oc project openshift
fi
